# Generated by Django 3.1.5 on 2022-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='service_type',
            field=models.CharField(blank=True, choices=[('lean', 'Lean'), ('deposit', 'Deposit')], max_length=255, null=True),
        ),
    ]
