# Generated by Django 3.1.5 on 2022-02-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220217_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
