# Generated by Django 3.1.5 on 2022-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220224_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='service_type',
            field=models.CharField(blank=True, choices=[('lean', 'Lean'), ('deposit', 'Deposit')], max_length=255, null=True),
        ),
    ]
