# Generated by Django 3.1.5 on 2022-05-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220307_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_is_active',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
