# Generated by Django 3.1.5 on 2022-05-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading_title', models.CharField(blank=True, max_length=255)),
                ('heading_subtitle', models.CharField(blank=True, max_length=255)),
                ('heading_image', models.ImageField(blank=True, upload_to='homepage/images/')),
                ('heading_image_alt', models.CharField(blank=True, max_length=255)),
                ('heading_image_caption', models.CharField(blank=True, max_length=255)),
                ('heading_content', models.TextField(blank=True)),
                ('heading_button_text', models.CharField(blank=True, max_length=255)),
                ('heading_button_link', models.CharField(blank=True, max_length=255)),
                ('heading_button_link_target_blank', models.BooleanField(default=False)),
                ('second_heading_button_text', models.CharField(blank=True, max_length=255)),
                ('second_heading_button_link', models.CharField(blank=True, max_length=255)),
                ('second_heading_button_link_target_blank', models.BooleanField(default=False)),
                ('first_section_title', models.CharField(blank=True, max_length=255)),
                ('first_section_subtitle', models.CharField(blank=True, max_length=255)),
                ('first_section_content', models.TextField(blank=True)),
                ('first_section_button_text', models.CharField(blank=True, max_length=255)),
                ('first_section_button_link', models.CharField(blank=True, max_length=255)),
                ('first_section_button_link_target_blank', models.BooleanField(default=False)),
                ('second_section_title', models.CharField(blank=True, max_length=255)),
                ('second_section_subtitle', models.CharField(blank=True, max_length=255)),
                ('second_section_content', models.TextField(blank=True)),
                ('second_section_button_text', models.CharField(blank=True, max_length=255)),
                ('second_section_button_link', models.CharField(blank=True, max_length=255)),
                ('second_section_button_link_target_blank', models.BooleanField(default=False)),
                ('third_section_title', models.CharField(blank=True, max_length=255)),
                ('third_section_subtitle', models.CharField(blank=True, max_length=255)),
                ('third_section_content', models.TextField(blank=True)),
                ('third_section_button_text', models.CharField(blank=True, max_length=255)),
                ('third_section_button_link', models.CharField(blank=True, max_length=255)),
                ('third_section_button_link_target_blank', models.BooleanField(default=False)),
                ('fourth_section_title', models.CharField(blank=True, max_length=255)),
                ('fourth_section_subtitle', models.CharField(blank=True, max_length=255)),
                ('fourth_section_content', models.TextField(blank=True)),
                ('fourth_section_button_text', models.CharField(blank=True, max_length=255)),
                ('fourth_section_button_link', models.CharField(blank=True, max_length=255)),
                ('fourth_section_button_link_target_blank', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='HomePageContentImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='homepage/images/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('homepage_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.homepagecontent')),
            ],
            options={
                'verbose_name': 'Homepage Content Image',
                'verbose_name_plural': 'Homepage Content Images',
            },
        ),
    ]
