# Generated by Django 3.1.5 on 2022-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuotUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about_us_title', models.CharField(blank=True, max_length=255)),
                ('about_us_subtitle', models.CharField(blank=True, max_length=255)),
                ('about_us_content', models.TextField(blank=True)),
                ('about_us_button_text', models.CharField(blank=True, max_length=255)),
                ('about_us_button_link', models.CharField(blank=True, max_length=255)),
                ('about_us_button_link_target_blank', models.BooleanField(default=False)),
                ('about_us_order', models.IntegerField(blank=True)),
                ('about_us_roadmap_title', models.CharField(blank=True, max_length=255)),
                ('about_us_roadmap_content', models.TextField(blank=True)),
                ('about_us_roadmap_button_text', models.CharField(blank=True, max_length=255)),
                ('about_us_roadmap_button_link', models.CharField(blank=True, max_length=255)),
                ('about_us_roadmap_button_link_target_blank', models.BooleanField(default=False)),
                ('about_us_roadmap_order', models.IntegerField(blank=True)),
                ('about_us_roadmap_image', models.ImageField(blank=True, upload_to='homepage/images/')),
                ('about_us_roadmap_image_alt', models.CharField(blank=True, max_length=255)),
                ('about_us_roadmap_image_caption', models.CharField(blank=True, max_length=255)),
                ('about_us_roadmap_image_order', models.IntegerField(blank=True)),
                ('about_us_roadmap_icon', models.ImageField(blank=True, upload_to='homepage/images/')),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
                'ordering': ['about_us_order'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(blank=True, max_length=255)),
                ('partner_image', models.ImageField(blank=True, upload_to='homepage/images/')),
                ('partner_image_alt', models.CharField(blank=True, max_length=255)),
                ('partner_image_caption', models.CharField(blank=True, max_length=255)),
                ('partner_link', models.CharField(blank=True, max_length=255)),
                ('partner_link_target_blank', models.BooleanField(default=False)),
                ('partner_order', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['partner_order'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('service_image', models.ImageField(blank=True, upload_to='homepage/images/')),
                ('service_image_alt', models.CharField(blank=True, max_length=255)),
                ('service_image_caption', models.CharField(blank=True, max_length=255)),
                ('service_content', models.TextField(blank=True)),
                ('service_button_text', models.CharField(blank=True, max_length=255)),
                ('service_button_link', models.CharField(blank=True, max_length=255)),
                ('service_button_link_target_blank', models.BooleanField(default=False)),
                ('service_order', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['service_order'],
            },
        ),
        migrations.DeleteModel(
            name='HomePageContentImage',
        ),
    ]
