# Generated by Django 3.1.5 on 2022-05-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20220513_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='heading_image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='heading_video_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
