# Generated by Django 3.1.5 on 2022-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20220514_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='partner_image_width',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
