# Generated by Django 3.1.5 on 2022-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_partners_partner_image_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('technology_name', models.CharField(blank=True, max_length=255)),
                ('technology_image', models.ImageField(blank=True, upload_to='homepage/images/')),
                ('technology_image_alt', models.CharField(blank=True, max_length=255)),
                ('technology_image_caption', models.CharField(blank=True, max_length=255)),
                ('technology_image_width', models.CharField(blank=True, max_length=255)),
                ('technology_link', models.CharField(blank=True, max_length=255)),
                ('technology_link_target_blank', models.BooleanField(default=False)),
                ('technology_order', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['technology_order'],
            },
        ),
        migrations.AddField(
            model_name='services',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='homepage.Technologies'),
        ),
    ]
