# Generated by Django 3.1.5 on 2022-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20220515_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('project_image', models.ImageField(blank=True, upload_to='homepage/images/')),
                ('project_image_alt', models.CharField(blank=True, max_length=255)),
                ('project_image_caption', models.CharField(blank=True, max_length=255)),
                ('project_image_width', models.CharField(blank=True, max_length=255)),
                ('project_link', models.CharField(blank=True, max_length=255)),
                ('project_link_target_blank', models.BooleanField(default=False)),
                ('project_order', models.IntegerField(blank=True)),
                ('project_partner', models.ManyToManyField(blank=True, to='homepage.Partners')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['project_order'],
            },
        ),
    ]
