# Generated by Django 3.1.5 on 2022-05-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_projects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_partner',
            new_name='project_partners',
        ),
    ]
