# Generated by Django 3.1.5 on 2022-05-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20220515_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_icon_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
