# Generated by Django 3.1.5 on 2022-05-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_services_service_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('team_cover_image', models.ImageField(blank=True, upload_to='homepage/images/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_member_name', models.CharField(blank=True, max_length=255)),
                ('team_member_role', models.CharField(blank=True, max_length=255)),
                ('team_member_image', models.ImageField(blank=True, upload_to='homepage/images/')),
                ('team_member_image_alt', models.CharField(blank=True, max_length=255)),
                ('team_member_image_caption', models.CharField(blank=True, max_length=255)),
                ('team_member_image_width', models.CharField(blank=True, max_length=255)),
                ('team_member_link', models.CharField(blank=True, max_length=255)),
                ('team_member_link_target_blank', models.BooleanField(default=False)),
                ('team_member_order', models.IntegerField(blank=True)),
            ],
        ),
    ]
