# Generated by Django 3.1.5 on 2022-05-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_team_teammembers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teammembers',
            options={'ordering': ['team_member_order'], 'verbose_name': 'Team Member', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, to='homepage.TeamMembers'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='team_member_image_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='team_member_projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
