# Generated by Django 3.1.5 on 2022-05-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20220517_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='technology_image_margin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
