# Generated by Django 3.1.5 on 2022-05-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_technologies_technology_image_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='partner_image_margin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
