# Generated by Django 3.1.5 on 2022-05-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_partners_partner_image_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='projects',
            field=models.ManyToManyField(blank=True, to='homepage.Projects'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
