# Generated by Django 3.1.5 on 2022-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20220517_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_projects_number',
            new_name='team_blockchain_projects_number',
        ),
        migrations.AddField(
            model_name='team',
            name='team_cyber_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_devops_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_mobile_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_web_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
