# Generated by Django 3.1.5 on 2022-05-17 14:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20220517_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_icon_color',
            field=colorfield.fields.ColorField(default='rgb(66, 102, 99)', image_field=None, max_length=18, samples=None),
        ),
    ]
