# Generated by Django 3.1.5 on 2022-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_services_service_icon_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='team_member_projects_completed',
            new_name='team_member_blockchain_projects_completed',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='team_member_mobile_projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='team_member_web_projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
