# Generated by Django 3.1.5 on 2022-05-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20220517_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_blockchain_projects_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_cyber_projects_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_devops_projects_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_mobile_projects_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_web_projects_number',
        ),
        migrations.AddField(
            model_name='projects',
            name='team_blockchain_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='team_cyber_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='team_devops_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='team_mobile_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='team_web_projects_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
