# Generated by Django 3.1.5 on 2022-05-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20220517_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_web_projects_number', models.IntegerField(blank=True, null=True)),
                ('team_mobile_projects_number', models.IntegerField(blank=True, null=True)),
                ('team_blockchain_projects_number', models.IntegerField(blank=True, null=True)),
                ('team_devops_projects_number', models.IntegerField(blank=True, null=True)),
                ('team_cyber_projects_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='team_blockchain_projects_number',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='team_cyber_projects_number',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='team_devops_projects_number',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='team_mobile_projects_number',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='team_web_projects_number',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_counts',
            field=models.ManyToManyField(blank=True, to='homepage.ProjectsCount'),
        ),
    ]
