# Generated by Django 3.1.5 on 2022-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20220517_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_counts',
        ),
        migrations.AddField(
            model_name='team',
            name='project_counts',
            field=models.ManyToManyField(blank=True, to='homepage.ProjectsCount'),
        ),
    ]
