# Generated by Django 3.1.5 on 2022-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0022_auto_20220519_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team_member_image',
            field=models.ImageField(blank=True, default='homepage/images/istockphoto-1356952644-170667a.jpg', upload_to='homepage/images/'),
        ),
    ]
