# Generated by Django 3.1.5 on 2022-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_auto_20220519_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='team_member_image',
            field=models.ImageField(blank=True, upload_to='homepage/images/'),
        ),
    ]
